name: BattleCoins
version: ${project.version}
main: dev.anhcraft.battlecoins.BattleCoins
depend: [CraftKit, Vault, Battle]
authors: [anhcraft]
api-version: "1.13"
description: BattleCoins
commands:
  bcoins:
    description: battlecoins
